image: harbor.duowan.com/front_end/node:12.7.0

before_script:
  - yarn config set registry https://npm-registry.duowan.com
  - yarn global add @yy/rv-cli

stages:
  - release

.release:
  stage: release
  tags:
    - webfe
  script:
    - rv .

# 发布 - 测试环境
release_test:
  extends: .release
  only:
    - test

# 发布 - 生产环境
release_prod:
  extends: .release
  when: manual
  only:
    - master
