const Koa = require('koaman')
const app = new Koa()

app
  .cors()
  .logger()
  .util()
  .errorHandler()
  // .upload(process.env.PATH_TMP)
  // .udpServe()
  // .udpService()
  // .redis()
  // .model()
  .service()
  .controller()
  .router()
  .start()
